---
apiVersion: v1
kind: Service
metadata:
  name: serverdash
  labels:
    app.kubernetes.io/name: serverdash
spec:
  ports:
  - port: 80
    targetPort: app-port
    protocol: TCP
    name: http

  selector:
    app.kubernetes.io/name: serverdash